name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -f Dockerfile-test -t github-actions-test:latest .
      - name: Run Docker image
        run: docker run --name github-actions-test github-actions-test:latest
